import './globals.css';
import { TaskProvider } from '../context/taskContext';
import { Inter } from 'next/font/google';
import { Toaster } from 'sonner';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <TaskProvider>
          {children}
          <Toaster richColors position='top-right' closeButton theme='dark'/>
        </TaskProvider>
      </body>
    </html>
  );
}
